
# Market Risk Integration Configuration

# Company information
company_name: Example Bank

# Data directories
data_dir: market_data
output_dir: risk_reports

# Capital configuration
capital_config: capital.yaml

# Portfolio settings
portfolio_file: portfolio.csv
demo_mode: true  # Set to false to require real portfolio data

# Risk analysis settings
lookback_days: 252  # One trading year (default if not auto-calibrated)
confidence_level: 0.99
var_horizon: 10
var_method: monte_carlo  # Options: parametric, historical, monte_carlo

# Auto-calibration settings
min_lookback_days: 125   # Minimum lookback to test
max_lookback_days: 1000  # Maximum lookback to test
lookback_step_size: 125  # Increment between tested lookbacks
accuracy_weight: 0.4     # Weight for accuracy in combined score
stability_weight: 0.3    # Weight for stability in combined score
coverage_weight: 0.2     # Weight for coverage in combined score
clustering_weight: 0.1   # Weight for clustering in combined score
min_stress_periods: 1    # Minimum number of stress periods to include
validation_test_size: 0.3  # Proportion of data to use for validation

# Risk factors to monitor
risk_factors:
  - ^GSPC  # S&P 500
  - ^VIX   # Volatility Index
  - DGS10  # 10-year Treasury Yield (FRED)
  - DEXUSEU  # USD/EUR Exchange Rate (FRED)
